#!/usr/bin/perl
# PODNAME: generate-wiki-from-pod
# Copyright (C) 2016-2017 SUSE LLC
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


use lib './lib';
use Mojo::File qw(path);
use Pod::POM;
use Pod::POM::View::Pod;

use Pod::Markdown::Github;
use File::Find;
use constant SUBMODULE_DIR => "../wiki/";
use constant LIBS_DIR      => "./lib/";
use constant BASE_URL      => "https://github.com/mudler/openQA/wiki/";
use feature 'say';
use DateTime;
use constant DATE => DateTime->now->hms . " " . DateTime->now->dmy('/');
use feature 'say';

sub modulepod2markdown {
    my $pod = Pod::POM->new();
    my $pom = $pod->parse_file( $_[0] ) || die $pod->error();
    my $markdown;
    my $parser = Pod::Markdown::Github->new( perldoc_url_prefix =>
            BASE_URL );
    $parser->output_string( \$markdown );
    $parser->parse_string_document( Pod::POM::View::Pod->print($pom) );
    path( SUBMODULE_DIR . $_[1],)->spurt($markdown) if $markdown =~ /[a-zA-Z]/g;
}

sub pull {
    my $b = shift;
    system("git pull");
    system("git merge origin " . $b );
    system("git submodule update");
}

sub commit {
    chdir(SUBMODULE_DIR);
    system("git checkout master");
    system("mv OpenQA.md Home.md");
    system("git add --all .");
    system(   "git commit -am 'Documentation automatic snapshot - "
            . DATE
            . "'; git push -u origin master" );

    chdir("../");
    system(
        "git commit -am 'Documentation automatic snapshot - " . DATE . "'" );
}

pull( $ARGV[0] ) if $ARGV[0];
chdir(LIBS_DIR);

find(
    {   wanted => sub {
            my $file = $_;
            next if ( !/\.pm$/ );
            s/\.\///;
            s/\.pm/\.md/;
            modulepod2markdown( $file, s/\//::/reg );
        },
        no_chdir => 1
    },
    "."
);

commit;
